import 'dart:convert';

class ProtectionPackageModel {
  final String id;
  final String title;
  final int stars;
  final String deductibleText;
  final String? deductibleColorHex;
  final double pricePerDay;
  final double? originalPricePerDay;
  final String? discountText;
  final String valueIdentifier;
  final Map<String, dynamic> features;

  ProtectionPackageModel({
    required this.id,
    required this.title,
    required this.stars,
    required this.deductibleText,
    this.deductibleColorHex,
    required this.pricePerDay,
    this.originalPricePerDay,
    this.discountText,
    required this.valueIdentifier,
    required this.features,
  });

  factory ProtectionPackageModel.fromJson(Map<String, dynamic> json) {
    return ProtectionPackageModel(
      id: json['id'],
      title: json['title'] ?? '',
      stars: json['stars'] ?? 1,
      deductibleText: json['deductibleText'] ?? '',
      deductibleColorHex: json['deductibleColorHex'],
      pricePerDay: (json['pricePerDay'] ?? 0.0).toDouble(),
      originalPricePerDay: json['originalPricePerDay'] != null ? (json['originalPricePerDay']).toDouble() : null,
      discountText: json['discountText'],
      valueIdentifier: json['valueIdentifier'] ?? 'basic',
      features: json['features'] ?? {},
    );
  }
}

class AddonModel {
  final String id;
  final String name;
  final double pricePerDay;
  final String iconIdentifier;

  AddonModel({
    required this.id,
    required this.name,
    required this.pricePerDay,
    required this.iconIdentifier,
  });

  factory AddonModel.fromJson(Map<String, dynamic> json) {
    return AddonModel(
      id: json['id'],
      name: json['name'] ?? '',
      pricePerDay: (json['pricePerDay'] ?? 0.0).toDouble(),
      iconIdentifier: json['iconIdentifier'] ?? '',
    );
  }
}

class MileagePackageModel {
  final String id;
  final String type; // 'LIMITED', 'UNLIMITED', 'PREMIUM_UNLIMITED'
  final double pricePerDay;
  final int? includedKm;
  final double? extraKmCharge;

  MileagePackageModel({
    required this.id,
    required this.type,
    required this.pricePerDay,
    this.includedKm,
    this.extraKmCharge,
  });

  factory MileagePackageModel.fromJson(Map<String, dynamic> json) {
    return MileagePackageModel(
      id: json['id'],
      type: json['type'] ?? 'UNLIMITED',
      pricePerDay: (json['pricePerDay'] ?? 0.0).toDouble(),
      includedKm: json['includedKm'],
      extraKmCharge: json['extraKmCharge'] != null ? (json['extraKmCharge']).toDouble() : null,
    );
  }
}

class CarModel {
  final String? id;
  final String name;
  final String type;
  final String supplier;
  final double? supplierLatitude;
  final double? supplierLongitude;
  final double rating;
  final String transmission;
  final String fuelType;
  final int seats;
  final int luggageCapacity;
  final List<String> features;
  final String supplierOption;
  final bool isSelfPickupAllowed;
  final bool isSupplierDeliveryAllowed;
  final bool isDoorstepDeliveryAllowed;
  final double pricePerDay;
  final double deliveryCharge;
  final String imageUrl;
  final List<ProtectionPackageModel> protectionPackages;
  final String? selectedProtectionPackageId;
  final List<MileagePackageModel> mileagePackages;
  final String? selectedMileagePackageId;
  final List<AddonModel> addons;
  final List<String>? selectedAddonIds;

  CarModel({
    this.id,
    required this.name,
    required this.type,
    required this.supplier,
    this.supplierLatitude,
    this.supplierLongitude,
    required this.rating,
    required this.transmission,
    required this.fuelType,
    required this.seats,
    required this.luggageCapacity,
    required this.features,
    required this.supplierOption,
    this.isSelfPickupAllowed = true,
    this.isSupplierDeliveryAllowed = false,
    this.isDoorstepDeliveryAllowed = false,
    required this.pricePerDay,
    this.deliveryCharge = 0.0,
    required this.imageUrl,
    this.protectionPackages = const [],
    this.selectedProtectionPackageId,
    this.mileagePackages = const [],
    this.selectedMileagePackageId,
    this.addons = const [],
    this.selectedAddonIds,
  });

  CarModel copyWith({
    String? id,
    String? name,
    String? type,
    String? supplier,
    double? supplierLatitude,
    double? supplierLongitude,
    double? rating,
    String? transmission,
    String? fuelType,
    int? seats,
    int? luggageCapacity,
    List<String>? features,
    String? supplierOption,
    bool? isSelfPickupAllowed,
    bool? isSupplierDeliveryAllowed,
    bool? isDoorstepDeliveryAllowed,
    double? pricePerDay,
    double? deliveryCharge,
    String? imageUrl,
    List<ProtectionPackageModel>? protectionPackages,
    String? selectedProtectionPackageId,
    List<MileagePackageModel>? mileagePackages,
    String? selectedMileagePackageId,
    List<AddonModel>? addons,
    List<String>? selectedAddonIds,
  }) {
    return CarModel(
      id: id ?? this.id,
      name: name ?? this.name,
      type: type ?? this.type,
      supplier: supplier ?? this.supplier,
      supplierLatitude: supplierLatitude ?? this.supplierLatitude,
      supplierLongitude: supplierLongitude ?? this.supplierLongitude,
      rating: rating ?? this.rating,
      transmission: transmission ?? this.transmission,
      fuelType: fuelType ?? this.fuelType,
      seats: seats ?? this.seats,
      luggageCapacity: luggageCapacity ?? this.luggageCapacity,
      features: features ?? this.features,
      supplierOption: supplierOption ?? this.supplierOption,
      isSelfPickupAllowed: isSelfPickupAllowed ?? this.isSelfPickupAllowed,
      isSupplierDeliveryAllowed: isSupplierDeliveryAllowed ?? this.isSupplierDeliveryAllowed,
      isDoorstepDeliveryAllowed: isDoorstepDeliveryAllowed ?? this.isDoorstepDeliveryAllowed,
      pricePerDay: pricePerDay ?? this.pricePerDay,
      deliveryCharge: deliveryCharge ?? this.deliveryCharge,
      imageUrl: imageUrl ?? this.imageUrl,
      protectionPackages: protectionPackages ?? this.protectionPackages,
      selectedProtectionPackageId: selectedProtectionPackageId ?? this.selectedProtectionPackageId,
      mileagePackages: mileagePackages ?? this.mileagePackages,
      selectedMileagePackageId: selectedMileagePackageId ?? this.selectedMileagePackageId,
      addons: addons ?? this.addons,
      selectedAddonIds: selectedAddonIds ?? this.selectedAddonIds,
    );
  }

  factory CarModel.fromJson(Map<String, dynamic> json) {
    return CarModel(
      id: json['id'],
      name: json['name'] ?? '',
      type: json['type'] ?? '',
      supplier: json['supplier'] ?? '',
      supplierLatitude: json['supplierLatitude'] != null ? (json['supplierLatitude'] as num).toDouble() : null,
      supplierLongitude: json['supplierLongitude'] != null ? (json['supplierLongitude'] as num).toDouble() : null,
      rating: json['rating'] != null ? (json['rating'] as num).toDouble() : 4.8,
      transmission: json['transmission'] ?? '',
      fuelType: json['fuelType'] ?? '',
      seats: json['seats'] ?? 0,
      luggageCapacity: json['luggageCapacity'] ?? 0,
      features: List<String>.from(json['features'] ?? []),
      supplierOption: json['supplierOption'] ?? '',
      isSelfPickupAllowed: json['isSelfPickupAllowed'] ?? true,
      isSupplierDeliveryAllowed: json['isSupplierDeliveryAllowed'] ?? false,
      isDoorstepDeliveryAllowed: json['isDoorstepDeliveryAllowed'] ?? false,
      pricePerDay: (json['pricePerDay'] ?? 0).toDouble(),
      deliveryCharge: (json['deliveryCharge'] ?? 0).toDouble(),
      imageUrl: json['imageUrl'] ?? '',
      protectionPackages: (json['protectionPackages'] as List<dynamic>?)
              ?.map((e) => ProtectionPackageModel.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      mileagePackages: (json['mileagePackages'] as List<dynamic>?)
              ?.map((e) => MileagePackageModel.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      addons: (json['addons'] as List<dynamic>?)
              ?.map((e) => AddonModel.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
    );
  }
}

final List<CarModel> mockCars = [
  CarModel(
    id: '810f7baf-aace-44a7-8cae-7f4b3e17b243',
    name: 'Toyota Corolla',
    type: 'Go - 5P',
    supplier: 'Elite Rentals',
    rating: 4.8,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    luggageCapacity: 2, seats: 5,
    features: ['A/C', 'Automatic', 'Unlimited Mileage'],
    supplierOption: 'Self Pickup',
    pricePerDay: 45.0,
    imageUrl: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&q=80&w=800',
    protectionPackages: [
      ProtectionPackageModel(
        id: '1',
        title: 'All Inclusive Protection',
        stars: 3,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 18.00,
        originalPricePerDay: 24.00,
        discountText: '- 25% online discount',
        valueIdentifier: 'all_inclusive',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': true,
          'Personal Accident Protection': true,
          'Roadside Protection': true,
        },
      ),
      ProtectionPackageModel(
        id: '2',
        title: 'Smart Protection',
        stars: 2,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 12.00,
        originalPricePerDay: 15.00,
        discountText: '- 20% online discount',
        valueIdentifier: 'smart',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
      ProtectionPackageModel(
        id: '3',
        title: 'Basic Protection',
        stars: 1,
        deductibleText: 'Deductible: up to €1,200.00',
        deductibleColorHex: '#000000',
        pricePerDay: 0.00,
        valueIdentifier: 'basic',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': false,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
    ],
    addons: [
      AddonModel(id: 'a1', name: 'GPS Navigation', pricePerDay: 10.00, iconIdentifier: 'navigation'),
      AddonModel(id: 'a2', name: 'Child Seat', pricePerDay: 6.00, iconIdentifier: 'child_care'),
      AddonModel(id: 'a3', name: 'Baby Seat', pricePerDay: 8.00, iconIdentifier: 'baby_changing_station'),
      AddonModel(id: 'a4', name: 'Booster Seat', pricePerDay: 4.00, iconIdentifier: 'event_seat'),
      AddonModel(id: 'a5', name: 'Phone Holder', pricePerDay: 2.00, iconIdentifier: 'phone_android'),
      AddonModel(id: 'a6', name: 'Wi-Fi Hotspot', pricePerDay: 5.00, iconIdentifier: 'wifi'),
    ],
  ),
  CarModel(
    id: '6ea25d2a-5e3a-4ffb-b017-09813d13f5e3',
    name: 'Mercedes Benz C-Class',
    type: 'Premium - 5P',
    supplier: 'Elite Rentals',
    rating: 4.9,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    luggageCapacity: 2, seats: 5,
    features: ['A/C', 'Automatic', 'Free Cancellation'],
    supplierOption: 'Self Pickup',
    pricePerDay: 85.0,
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=800',
    protectionPackages: [
      ProtectionPackageModel(
        id: '1',
        title: 'All Inclusive Protection',
        stars: 3,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 18.00,
        originalPricePerDay: 24.00,
        discountText: '- 25% online discount',
        valueIdentifier: 'all_inclusive',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': true,
          'Personal Accident Protection': true,
          'Roadside Protection': true,
        },
      ),
      ProtectionPackageModel(
        id: '2',
        title: 'Smart Protection',
        stars: 2,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 12.00,
        originalPricePerDay: 15.00,
        discountText: '- 20% online discount',
        valueIdentifier: 'smart',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
      ProtectionPackageModel(
        id: '3',
        title: 'Basic Protection',
        stars: 1,
        deductibleText: 'Deductible: up to €1,200.00',
        deductibleColorHex: '#000000',
        pricePerDay: 0.00,
        valueIdentifier: 'basic',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': false,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
    ],
    addons: [
      AddonModel(id: 'a1', name: 'GPS Navigation', pricePerDay: 10.00, iconIdentifier: 'navigation'),
      AddonModel(id: 'a2', name: 'Child Seat', pricePerDay: 6.00, iconIdentifier: 'child_care'),
      AddonModel(id: 'a3', name: 'Baby Seat', pricePerDay: 8.00, iconIdentifier: 'baby_changing_station'),
      AddonModel(id: 'a4', name: 'Booster Seat', pricePerDay: 4.00, iconIdentifier: 'event_seat'),
      AddonModel(id: 'a5', name: 'Phone Holder', pricePerDay: 2.00, iconIdentifier: 'phone_android'),
      AddonModel(id: 'a6', name: 'Wi-Fi Hotspot', pricePerDay: 5.00, iconIdentifier: 'wifi'),
    ],
  ),
  CarModel(
    id: '97546466-13ea-4428-9f2f-bc950babaa0d',
    name: 'Toyota RAV4',
    type: 'SUV - 7P',
    supplier: 'Adventure Rentals',
    rating: 4.7,
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    luggageCapacity: 2, seats: 7,
    features: ['A/C', 'Automatic', 'Instant Confirmation'],
    supplierOption: 'Supplier Delivery',
    pricePerDay: 65.0,
    imageUrl: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&q=80&w=800',
    protectionPackages: [
      ProtectionPackageModel(
        id: '1',
        title: 'All Inclusive Protection',
        stars: 3,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 18.00,
        originalPricePerDay: 24.00,
        discountText: '- 25% online discount',
        valueIdentifier: 'all_inclusive',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': true,
          'Personal Accident Protection': true,
          'Roadside Protection': true,
        },
      ),
      ProtectionPackageModel(
        id: '2',
        title: 'Smart Protection',
        stars: 2,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 12.00,
        originalPricePerDay: 15.00,
        discountText: '- 20% online discount',
        valueIdentifier: 'smart',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
      ProtectionPackageModel(
        id: '3',
        title: 'Basic Protection',
        stars: 1,
        deductibleText: 'Deductible: up to €1,200.00',
        deductibleColorHex: '#000000',
        pricePerDay: 0.00,
        valueIdentifier: 'basic',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': false,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
    ],
    addons: [
      AddonModel(id: 'a1', name: 'GPS Navigation', pricePerDay: 10.00, iconIdentifier: 'navigation'),
      AddonModel(id: 'a2', name: 'Child Seat', pricePerDay: 6.00, iconIdentifier: 'child_care'),
      AddonModel(id: 'a3', name: 'Baby Seat', pricePerDay: 8.00, iconIdentifier: 'baby_changing_station'),
      AddonModel(id: 'a4', name: 'Booster Seat', pricePerDay: 4.00, iconIdentifier: 'event_seat'),
      AddonModel(id: 'a5', name: 'Phone Holder', pricePerDay: 2.00, iconIdentifier: 'phone_android'),
      AddonModel(id: 'a6', name: 'Wi-Fi Hotspot', pricePerDay: 5.00, iconIdentifier: 'wifi'),
    ],
  ),
  CarModel(
    id: 'addcf49c-cb67-4e5f-901d-2d956910a42b',
    name: 'Nissan Leaf',
    type: 'Electric - 5P',
    supplier: 'Eco Rentals',
    rating: 4.5,
    transmission: 'Automatic',
    fuelType: 'Electric',
    luggageCapacity: 2, seats: 5,
    features: ['A/C', 'Automatic', 'Unlimited Mileage'],
    supplierOption: 'Self Pickup',
    pricePerDay: 50.0,
    imageUrl: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&q=80&w=800',
    protectionPackages: [
      ProtectionPackageModel(
        id: '1',
        title: 'All Inclusive Protection',
        stars: 3,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 18.00,
        originalPricePerDay: 24.00,
        discountText: '- 25% online discount',
        valueIdentifier: 'all_inclusive',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': true,
          'Personal Accident Protection': true,
          'Roadside Protection': true,
        },
      ),
      ProtectionPackageModel(
        id: '2',
        title: 'Smart Protection',
        stars: 2,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 12.00,
        originalPricePerDay: 15.00,
        discountText: '- 20% online discount',
        valueIdentifier: 'smart',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
      ProtectionPackageModel(
        id: '3',
        title: 'Basic Protection',
        stars: 1,
        deductibleText: 'Deductible: up to €1,200.00',
        deductibleColorHex: '#000000',
        pricePerDay: 0.00,
        valueIdentifier: 'basic',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': false,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
    ],
    addons: [
      AddonModel(id: 'a1', name: 'GPS Navigation', pricePerDay: 10.00, iconIdentifier: 'navigation'),
      AddonModel(id: 'a2', name: 'Child Seat', pricePerDay: 6.00, iconIdentifier: 'child_care'),
      AddonModel(id: 'a3', name: 'Baby Seat', pricePerDay: 8.00, iconIdentifier: 'baby_changing_station'),
      AddonModel(id: 'a4', name: 'Booster Seat', pricePerDay: 4.00, iconIdentifier: 'event_seat'),
      AddonModel(id: 'a5', name: 'Phone Holder', pricePerDay: 2.00, iconIdentifier: 'phone_android'),
      AddonModel(id: 'a6', name: 'Wi-Fi Hotspot', pricePerDay: 5.00, iconIdentifier: 'wifi'),
    ],
  ),
  CarModel(
    id: '9287cbe7-e407-4fd8-87b1-cf4e01e0e71a',
    name: 'Ford Transit',
    type: 'Van - 8P & Above',
    supplier: 'Big Van Rentals',
    rating: 4.3,
    transmission: 'Manual',
    fuelType: 'Diesel',
    luggageCapacity: 2, seats: 8,
    features: ['A/C', 'Manual'],
    supplierOption: 'Supplier Delivery',
    pricePerDay: 90.0,
    imageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800',
    protectionPackages: [
      ProtectionPackageModel(
        id: '1',
        title: 'All Inclusive Protection',
        stars: 3,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 18.00,
        originalPricePerDay: 24.00,
        discountText: '- 25% online discount',
        valueIdentifier: 'all_inclusive',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': true,
          'Personal Accident Protection': true,
          'Roadside Protection': true,
        },
      ),
      ProtectionPackageModel(
        id: '2',
        title: 'Smart Protection',
        stars: 2,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 12.00,
        originalPricePerDay: 15.00,
        discountText: '- 20% online discount',
        valueIdentifier: 'smart',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
      ProtectionPackageModel(
        id: '3',
        title: 'Basic Protection',
        stars: 1,
        deductibleText: 'Deductible: up to €1,200.00',
        deductibleColorHex: '#000000',
        pricePerDay: 0.00,
        valueIdentifier: 'basic',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': false,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
    ],
    addons: [
      AddonModel(id: 'a1', name: 'GPS Navigation', pricePerDay: 10.00, iconIdentifier: 'navigation'),
      AddonModel(id: 'a2', name: 'Child Seat', pricePerDay: 6.00, iconIdentifier: 'child_care'),
      AddonModel(id: 'a3', name: 'Baby Seat', pricePerDay: 8.00, iconIdentifier: 'baby_changing_station'),
      AddonModel(id: 'a4', name: 'Booster Seat', pricePerDay: 4.00, iconIdentifier: 'event_seat'),
      AddonModel(id: 'a5', name: 'Phone Holder', pricePerDay: 2.00, iconIdentifier: 'phone_android'),
      AddonModel(id: 'a6', name: 'Wi-Fi Hotspot', pricePerDay: 5.00, iconIdentifier: 'wifi'),
    ],
  ),
  CarModel(
    id: '9755baea-9e6d-4e7c-8271-66439aae00de',
    name: 'Honda Civic',
    type: 'Go - 5P',
    supplier: 'City Rentals',
    rating: 4.6,
    transmission: 'Manual',
    fuelType: 'Petrol',
    luggageCapacity: 2, seats: 5,
    features: ['A/C', 'Manual', 'Free Cancellation'],
    supplierOption: 'Self Pickup',
    pricePerDay: 40.0,
    imageUrl: 'https://images.unsplash.com/photo-1605810711152-78d145f471e9?auto=format&fit=crop&q=80&w=800',
    protectionPackages: [
      ProtectionPackageModel(
        id: '1',
        title: 'All Inclusive Protection',
        stars: 3,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 18.00,
        originalPricePerDay: 24.00,
        discountText: '- 25% online discount',
        valueIdentifier: 'all_inclusive',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': true,
          'Personal Accident Protection': true,
          'Roadside Protection': true,
        },
      ),
      ProtectionPackageModel(
        id: '2',
        title: 'Smart Protection',
        stars: 2,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 12.00,
        originalPricePerDay: 15.00,
        discountText: '- 20% online discount',
        valueIdentifier: 'smart',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
      ProtectionPackageModel(
        id: '3',
        title: 'Basic Protection',
        stars: 1,
        deductibleText: 'Deductible: up to €1,200.00',
        deductibleColorHex: '#000000',
        pricePerDay: 0.00,
        valueIdentifier: 'basic',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': false,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
    ],
    addons: [
      AddonModel(id: 'a1', name: 'GPS Navigation', pricePerDay: 10.00, iconIdentifier: 'navigation'),
      AddonModel(id: 'a2', name: 'Child Seat', pricePerDay: 6.00, iconIdentifier: 'child_care'),
      AddonModel(id: 'a3', name: 'Baby Seat', pricePerDay: 8.00, iconIdentifier: 'baby_changing_station'),
      AddonModel(id: 'a4', name: 'Booster Seat', pricePerDay: 4.00, iconIdentifier: 'event_seat'),
      AddonModel(id: 'a5', name: 'Phone Holder', pricePerDay: 2.00, iconIdentifier: 'phone_android'),
      AddonModel(id: 'a6', name: 'Wi-Fi Hotspot', pricePerDay: 5.00, iconIdentifier: 'wifi'),
    ],
  ),
  CarModel(
    id: 'f5b0af2b-095a-44c5-876d-30b65f00d329',
    name: 'Audi Q5',
    type: 'SUV - 7P',
    supplier: 'Premium Drives',
    rating: 4.9,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    luggageCapacity: 2, seats: 7,
    features: ['A/C', 'Automatic', 'Unlimited Mileage', 'Free Cancellation'],
    supplierOption: 'Supplier Delivery',
    pricePerDay: 110.0,
    imageUrl: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=800',
    protectionPackages: [
      ProtectionPackageModel(
        id: '1',
        title: 'All Inclusive Protection',
        stars: 3,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 18.00,
        originalPricePerDay: 24.00,
        discountText: '- 25% online discount',
        valueIdentifier: 'all_inclusive',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': true,
          'Personal Accident Protection': true,
          'Roadside Protection': true,
        },
      ),
      ProtectionPackageModel(
        id: '2',
        title: 'Smart Protection',
        stars: 2,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 12.00,
        originalPricePerDay: 15.00,
        discountText: '- 20% online discount',
        valueIdentifier: 'smart',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
      ProtectionPackageModel(
        id: '3',
        title: 'Basic Protection',
        stars: 1,
        deductibleText: 'Deductible: up to €1,200.00',
        deductibleColorHex: '#000000',
        pricePerDay: 0.00,
        valueIdentifier: 'basic',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': false,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
    ],
    addons: [
      AddonModel(id: 'a1', name: 'GPS Navigation', pricePerDay: 10.00, iconIdentifier: 'navigation'),
      AddonModel(id: 'a2', name: 'Child Seat', pricePerDay: 6.00, iconIdentifier: 'child_care'),
      AddonModel(id: 'a3', name: 'Baby Seat', pricePerDay: 8.00, iconIdentifier: 'baby_changing_station'),
      AddonModel(id: 'a4', name: 'Booster Seat', pricePerDay: 4.00, iconIdentifier: 'event_seat'),
      AddonModel(id: 'a5', name: 'Phone Holder', pricePerDay: 2.00, iconIdentifier: 'phone_android'),
      AddonModel(id: 'a6', name: 'Wi-Fi Hotspot', pricePerDay: 5.00, iconIdentifier: 'wifi'),
    ],
  ),
  CarModel(
    id: 'a34dbc48-b4de-483e-9f2b-b93c07d7010b',
    name: 'Tesla Model 3',
    type: 'Electric - 5P',
    supplier: 'Future Rides',
    rating: 4.9,
    transmission: 'Automatic',
    fuelType: 'Electric',
    luggageCapacity: 2, seats: 5,
    features: ['A/C', 'Automatic', 'Unlimited Mileage', 'Instant Confirmation'],
    supplierOption: 'Self Pickup',
    pricePerDay: 75.0,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&q=80&w=800',
    protectionPackages: [
      ProtectionPackageModel(
        id: '1',
        title: 'All Inclusive Protection',
        stars: 3,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 18.00,
        originalPricePerDay: 24.00,
        discountText: '- 25% online discount',
        valueIdentifier: 'all_inclusive',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': true,
          'Personal Accident Protection': true,
          'Roadside Protection': true,
        },
      ),
      ProtectionPackageModel(
        id: '2',
        title: 'Smart Protection',
        stars: 2,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 12.00,
        originalPricePerDay: 15.00,
        discountText: '- 20% online discount',
        valueIdentifier: 'smart',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
      ProtectionPackageModel(
        id: '3',
        title: 'Basic Protection',
        stars: 1,
        deductibleText: 'Deductible: up to €1,200.00',
        deductibleColorHex: '#000000',
        pricePerDay: 0.00,
        valueIdentifier: 'basic',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': false,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
    ],
    addons: [
      AddonModel(id: 'a1', name: 'GPS Navigation', pricePerDay: 10.00, iconIdentifier: 'navigation'),
      AddonModel(id: 'a2', name: 'Child Seat', pricePerDay: 6.00, iconIdentifier: 'child_care'),
      AddonModel(id: 'a3', name: 'Baby Seat', pricePerDay: 8.00, iconIdentifier: 'baby_changing_station'),
      AddonModel(id: 'a4', name: 'Booster Seat', pricePerDay: 4.00, iconIdentifier: 'event_seat'),
      AddonModel(id: 'a5', name: 'Phone Holder', pricePerDay: 2.00, iconIdentifier: 'phone_android'),
      AddonModel(id: 'a6', name: 'Wi-Fi Hotspot', pricePerDay: 5.00, iconIdentifier: 'wifi'),
    ],
  ),
  CarModel(
    id: 'e8544c08-845b-43fc-8be2-ef749fa02412',
    name: 'Volkswagen Golf',
    type: 'Go - 5P',
    supplier: 'Budget Rentals',
    rating: 4.4,
    transmission: 'Manual',
    fuelType: 'Diesel',
    luggageCapacity: 2, seats: 5,
    features: ['A/C', 'Manual', 'Unlimited Mileage'],
    supplierOption: 'Self Pickup',
    pricePerDay: 35.0,
    imageUrl: 'https://images.unsplash.com/photo-1629897148507-6cb56ec2303f?auto=format&fit=crop&q=80&w=800',
    protectionPackages: [
      ProtectionPackageModel(
        id: '1',
        title: 'All Inclusive Protection',
        stars: 3,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 18.00,
        originalPricePerDay: 24.00,
        discountText: '- 25% online discount',
        valueIdentifier: 'all_inclusive',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': true,
          'Personal Accident Protection': true,
          'Roadside Protection': true,
        },
      ),
      ProtectionPackageModel(
        id: '2',
        title: 'Smart Protection',
        stars: 2,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 12.00,
        originalPricePerDay: 15.00,
        discountText: '- 20% online discount',
        valueIdentifier: 'smart',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
      ProtectionPackageModel(
        id: '3',
        title: 'Basic Protection',
        stars: 1,
        deductibleText: 'Deductible: up to €1,200.00',
        deductibleColorHex: '#000000',
        pricePerDay: 0.00,
        valueIdentifier: 'basic',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': false,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
    ],
    addons: [
      AddonModel(id: 'a1', name: 'GPS Navigation', pricePerDay: 10.00, iconIdentifier: 'navigation'),
      AddonModel(id: 'a2', name: 'Child Seat', pricePerDay: 6.00, iconIdentifier: 'child_care'),
      AddonModel(id: 'a3', name: 'Baby Seat', pricePerDay: 8.00, iconIdentifier: 'baby_changing_station'),
      AddonModel(id: 'a4', name: 'Booster Seat', pricePerDay: 4.00, iconIdentifier: 'event_seat'),
      AddonModel(id: 'a5', name: 'Phone Holder', pricePerDay: 2.00, iconIdentifier: 'phone_android'),
      AddonModel(id: 'a6', name: 'Wi-Fi Hotspot', pricePerDay: 5.00, iconIdentifier: 'wifi'),
    ],
  ),
  CarModel(
    id: 'd1f8788a-bd22-4267-a0ce-634fa18a9191',
    name: 'BMW 5 Series',
    type: 'Premium - 5P',
    supplier: 'Elite Rentals',
    rating: 4.8,
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    luggageCapacity: 2, seats: 5,
    features: ['A/C', 'Automatic', 'Free Cancellation', 'Instant Confirmation'],
    supplierOption: 'Supplier Delivery',
    pricePerDay: 95.0,
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=800',
    protectionPackages: [
      ProtectionPackageModel(
        id: '1',
        title: 'All Inclusive Protection',
        stars: 3,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 18.00,
        originalPricePerDay: 24.00,
        discountText: '- 25% online discount',
        valueIdentifier: 'all_inclusive',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': true,
          'Personal Accident Protection': true,
          'Roadside Protection': true,
        },
      ),
      ProtectionPackageModel(
        id: '2',
        title: 'Smart Protection',
        stars: 2,
        deductibleText: 'No deductible',
        deductibleColorHex: '#4CAF50',
        pricePerDay: 12.00,
        originalPricePerDay: 15.00,
        discountText: '- 20% online discount',
        valueIdentifier: 'smart',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': true,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
      ProtectionPackageModel(
        id: '3',
        title: 'Basic Protection',
        stars: 1,
        deductibleText: 'Deductible: up to €1,200.00',
        deductibleColorHex: '#000000',
        pricePerDay: 0.00,
        valueIdentifier: 'basic',
        features: {
          'Loss Damage Waiver (including theft protection)': true,
          'Tyre & Glass Protection': false,
          'Interior Protection': false,
          'Personal Accident Protection': false,
          'Roadside Protection': false,
        },
      ),
    ],
    addons: [
      AddonModel(id: 'a1', name: 'GPS Navigation', pricePerDay: 10.00, iconIdentifier: 'navigation'),
      AddonModel(id: 'a2', name: 'Child Seat', pricePerDay: 6.00, iconIdentifier: 'child_care'),
      AddonModel(id: 'a3', name: 'Baby Seat', pricePerDay: 8.00, iconIdentifier: 'baby_changing_station'),
      AddonModel(id: 'a4', name: 'Booster Seat', pricePerDay: 4.00, iconIdentifier: 'event_seat'),
      AddonModel(id: 'a5', name: 'Phone Holder', pricePerDay: 2.00, iconIdentifier: 'phone_android'),
      AddonModel(id: 'a6', name: 'Wi-Fi Hotspot', pricePerDay: 5.00, iconIdentifier: 'wifi'),
    ],
  ),
];
