// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4d4yofxtVY3h5iCA6qzz5KL_h5vf6Qwg',
    appId: '1:715853709143:web:c04225fbc714b9f1494812',
    messagingSenderId: '715853709143',
    projectId: 'numbers-9f9f6',
    authDomain: 'numbers-9f9f6.firebaseapp.com',
    storageBucket: 'numbers-9f9f6.firebasestorage.app',
    measurementId: 'G-F7SG5XXWVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDridqV09-x8J8EdVSsrQElGsCbBWRJJcc',
    appId: '1:715853709143:android:6b36f4393bf3e7a1494812',
    messagingSenderId: '715853709143',
    projectId: 'numbers-9f9f6',
    authDomain: 'numbers-9f9f6.firebaseapp.com',
    storageBucket: 'numbers-9f9f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa722axSSj5ggXMJ-wi8UG29VbwxmppVA',
    appId: '1:715853709143:ios:c9e1c6c3558b4655494812',
    messagingSenderId: '715853709143',
    projectId: 'numbers-9f9f6',
    storageBucket: 'numbers-9f9f6.firebasestorage.app',
    iosBundleId: 'com.gozolt.gozoltUserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa722axSSj5ggXMJ-wi8UG29VbwxmppVA',
    appId: '1:715853709143:ios:c9e1c6c3558b4655494812',
    messagingSenderId: '715853709143',
    projectId: 'numbers-9f9f6',
    storageBucket: 'numbers-9f9f6.firebasestorage.app',
    iosBundleId: 'com.gozolt.gozoltUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4d4yofxtVY3h5iCA6qzz5KL_h5vf6Qwg',
    appId: '1:715853709143:web:347e13c9334bd2cc494812',
    messagingSenderId: '715853709143',
    projectId: 'numbers-9f9f6',
    authDomain: 'numbers-9f9f6.firebaseapp.com',
    storageBucket: 'numbers-9f9f6.firebasestorage.app',
    measurementId: 'G-ZZS4Q29X8S',
  );

}